### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by ahadabasi** [kylelogue/tinyMCE-image-upload-plugin-for-laravel#2]
Hi
I get an error 
Failed to load plugin: imageupload from url http://cdn.tinymce.com/4/plugins/imageupload/plugin.min.js

[The error](https://ibb.co/jbVy1F)

**Comment by janvleugels** [comment]
Probably because you load your TinyMce from cdn. You need to put all files on your server, and add plugins there
